# Generated by Django 4.1.1 on 2022-09-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Item',
        ),
    ]
