# Generated by Django 4.1.1 on 2022-11-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_itemdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdescription',
            name='photo',
            field=models.ImageField(null=True, upload_to='description_photo'),
        ),
    ]
